BEGIN;

ALTER TABLE company_settings
  ADD COLUMN IF NOT EXISTS emailfrom VARCHAR(255),
  ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255),
  ADD COLUMN IF NOT EXISTS smtp_port INT,
  ADD COLUMN IF NOT EXISTS smtp_secure BOOLEAN,
  ADD COLUMN IF NOT EXISTS smtp_user VARCHAR(255),
  ADD COLUMN IF NOT EXISTS smtp_pass TEXT,
  ADD COLUMN IF NOT EXISTS gmail_user VARCHAR(255),
  ADD COLUMN IF NOT EXISTS gmail_pass TEXT;

COMMIT;